### ISSUE TITLE
Commande mettre à jour les cordonnées : libellé inversé sur latitude longitude

### ISSUE THREAD

**Issue by Bosquetia** [lunarok/jeedom_geotrav#31]
Dans un scénario si on utilise la commande mettre à jour les coordonnées d'un équipement geotrav
le libellé qui apparait fait une inversion longitude,latitude.
Cela peut induire les gens en erreur

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_geotrav/commit/7f9bb91619afcec0a93842b5f4f87a57916e73f7
