### ISSUE TITLE
Pas de lien / dépendance entre les équipements

### ISSUE THREAD

**Issue by BadWolf42** [lunarok/jeedom_geotrav#45]
Bonjour Lunarok,

Comme on peut le voir sur la capture d'écran ci-dessous prise depuis "Appart" :
![2018-12-25_094242](https://user-images.githubusercontent.com/8396512/50418040-b67f7b00-0829-11e9-9806-cbf6f21187d4.png)
"Geofence" utilise "Appart" et pourtant il n'y a pas de connexion entre eux.

De même pour "Soleil" du plugin Heliotrope qui utilise aussi "Appart" :
![2018-12-25_094829](https://user-images.githubusercontent.com/8396512/50418155-44f3fc80-082a-11e9-84d1-022345c252f8.png)
Mais pour ça je pense qu'il est préférable que j'ouvre un bug sur Héliotrope, non ?

Merci

**Comment by lunarok** [comment]
Pas possible, cette carte ne permet de lier des equipements qu'aux
commandes, objets et scénarios. Pas à d'autres equipements.

**Comment by BadWolf42** [comment]
Merci de m'avoir répondu, je comprend la limitation.
Si on passe outre la carte, le problème est selon moi plus profond : il n'est nul-part indiqué quel autre équipement est utilisé un équipement Géotrav, s'il ne consomme pas ses commandes.
Par exemple, ci-dessus, si on souhaite supprimer "Appart", on a l’impression qu'il n'est utilisé par rien.
Ca me semble un axe d'amélioration, peut-être pas prioritaire au vu de nombreux plugins que vous maintenez, mais au moins légitime, non ?

**Comment by lunarok** [comment]
Oui, sauf que cette carte apparait où ? Elle n'est pas lié à mon plugin
mais au core. Et pour la construire les liens entre équipements ne sont pas
regardé. Je pourrais rien y faire, ca ne relève pas d'un des plugins.
