### ISSUE TITLE
Localisation par adresse ou coordonnées

### ISSUE THREAD

**Issue by Ethal** [lunarok/jeedom_geotrav#7]
Bonjour,
je commence à regarder ton nouveau plugin, 
pour éviter le probleme si une personne rentre les coordonnées ET l'adresse avec l'option localisation , peut etre dans dans le menu déroulant fair une option "localisation par coordonnées" et une option "localisation par adresse" , puisque ensuite dans les commandes on a les deux et ne garder qu'une "commande mettre à jour"
Tu en penses quoi ?

**Comment by lunarok** [comment]
je serais même plutot tenté de supprimé le champ coordonnées à cet endroit en fait, à utiliser avec le champ adresse je fais plus que ca dans les tests ca va plus vite

**Comment by Ethal** [comment]
Bonjour,
Il y a beaucoup d'adresse en France qui sont des lieux dit , et il arrive que dans ce lieu il y ai plus d'une habitation, voir meme des fois des corps de fermes et des maisons,  
donc pour les personnes habitants ces lieux dit je pense que l'utilisation des coordonnées est nécessaire , j'ai fait le test avec des adresses que je connais bien (ie famille) , et c'était pas très concluant. 
Donc je suis plus partagé pour la suppression de l'option coordonnées.

**Comment by lunarok** [comment]
Effectivement pas trop jouer avec les adresses de campagne. Donc oui un sélect d'abord en adresse par défaut.
La j'ai encore les transports navitia a mettre, 3 widgets et la génération des cmds pour geofence (geofence je ferais aussi une présence sur polygone en option avancé)

**Comment by Ethal** [comment]
Bonsoir,
ça marche, je te laisse avancer, peut être fait des remarques trop tot ;)
mais je suis ce plugin avec attention.
