### ISSUE TITLE
Modification du nom de la commande et suppression de celle-ci

### ISSUE THREAD

**Issue by Ethal** [lunarok/jeedom_geotrav#8]
Bonjour,
Concernant l'onglet commande,
Y a t il un intérêt à pouvoir supprimer une commande et à renommer celle-ci, ?
si ce n'est que de laisser le choix au utilisateur étranger de personnaliser , mais pour cela il y a les traductions.
je peux te faire le commit si tu es ok

**Comment by lunarok** [comment]
oui oui y a un intérêt, je vais modifier geofence pour avoir un bouton de génération des commandes et pouvoir supprimer complètement celles qu'on souhaitent pas
ca fait moins bordélique sur la page

**Comment by Ethal** [comment]
ok ca marche, je regarderais ça quand tu auras fait la modif
